name: CI - Multi Project Pipeline

on:
  pull_request:
    branches: 
      - master


permissions:
  actions: write
  contents: write
  security-events: write
  issues: write
##sassa
jobs:
  pr-pipeline:
    uses: PruebaActions/WorkFlows-Templates/.github/workflows/probando-local.yaml@main
    with:
      projects_json: '{
        "include": [
          {
            "project_name": "UVC.Web",
            "solution_path": "./DescopeSampleApp.sln",
            "project_path": "./DescopeSampleApp/DescopeSampleApp.csproj",
            "project_type": "framework",
            "deploy_target_path": "C:\\inetpub\\wwwroot\\artifact"
          }
        ]
      }'

      runner_tag: '["self-hosted", "windows", "x64", "laptop"]'

      e2e_tests_json: |
      [
        "klk"
      ]



    
      #project_path: "./DescopeSampleApp/DescopeSampleApp.csproj"
      #solution_path: "./DescopeSampleApp.sln"
      #project_type: "framework"



      
      #     project_paths: |
      #   [
      #     { "path": "./DescopeSampleApp.sln", "isFramework": "true", "language": "csharp" }
      #   ]
      # test_paths: '[]'
      # codeql_languages: 'csharp'
      # solution_path_codeql: './DescopeSampleApp.sln'
      # solution_isFramework_codeql: 'true'
      # docker_targets: |
      #   [
      #     {
      #       "image_name": "descopesampleapp-pr",
      #       "container_name": "descopesampleapp-pr-container",
      #       "dockerfile": "./DescopeSampleApp/Dockerfile",
      #       "container_port": "80",
      #       "isFramework": "true"
      #     }
      #   ]




# name: Pull Request Pipeline

# on:
#   pull_request:
#     branches:
#       - master


# permissions:
#   actions: read
#   contents: read
#   security-events: write
#   issues: write

# jobs:
#   pr-pipeline:
#     uses: PruebaActions/WorkFlows-Templates/.github/workflows/pr-dotnet-codeql.yaml@main
#     with:
#       image_name: descopesampleapp-pr
#       container_name: descopesampleapp-pr-container
#       dockerfile: ./DescopeSampleApp/Dockerfile              # El Dockerfile está en la raíz del proyecto                    # Puerto en la máquina host
#       container_port: '80'                  # IIS dentro del contenedor suele usar el 80
#       #codeql_languages: 'csharp'
#       project_paths: '["./DescopeSampleApp.sln"]'
#       has_tests: false                      # ponlo en true si luego agregas un proyecto de pruebas
